version: '3.9'
services:
  web:
    build: web
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./web
        target: /web
  server:
    build: server
    ports:
      - "3333:3333"
    volumes:
      - type: bind
        source: ./server
        target: /server
