version: '3.9'
services:
  web:
    container_name: web
    build: web
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./web
        target: /web
  server:
    container_name: server
    build: server
    ports:
      - "3333:3333"
      - "5555:5555"
    volumes:
      - type: bind
        source: ./server
        target: /server
  mobile:
    container_name: mobile
    build: mobile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19003:19003"
      - "19004:19004"
      - "19005:19005"
      - "19006:19006"
    volumes:
      - type: bind
        source: ./mobile
        target: /mobile
    environment:        
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
